//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class ErrorLog : XPLiteObject
    {
        int fidErrorLog;
        [Key(true)]
        public int idErrorLog
        {
            get { return fidErrorLog; }
            set { SetPropertyValue<int>("idErrorLog", ref fidErrorLog, value); }
        }
        string fErrorMsg;
        [Size(5000)]
        public string ErrorMsg
        {
            get { return fErrorMsg; }
            set { SetPropertyValue<string>("ErrorMsg", ref fErrorMsg, value); }
        }
        int fidPrijava;
        public int idPrijava
        {
            get { return fidPrijava; }
            set { SetPropertyValue<int>("idPrijava", ref fidPrijava, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
    }

}
