//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class Izplacila : XPLiteObject
    {
        int fidIzplacilla;
        [Key(true)]
        public int idIzplacilla
        {
            get { return fidIzplacilla; }
            set { SetPropertyValue<int>("idIzplacilla", ref fidIzplacilla, value); }
        }
        Users fIdUser;
        [Association(@"IzplacilaReferencesUsers")]
        public Users IdUser
        {
            get { return fIdUser; }
            set { SetPropertyValue<Users>("IdUser", ref fIdUser, value); }
        }
        DateTime fDatumOd;
        public DateTime DatumOd
        {
            get { return fDatumOd; }
            set { SetPropertyValue<DateTime>("DatumOd", ref fDatumOd, value); }
        }
        DateTime fDatumDo;
        public DateTime DatumDo
        {
            get { return fDatumDo; }
            set { SetPropertyValue<DateTime>("DatumDo", ref fDatumDo, value); }
        }
        string fMesec;
        [Size(20)]
        public string Mesec
        {
            get { return fMesec; }
            set { SetPropertyValue<string>("Mesec", ref fMesec, value); }
        }
        int fLeto;
        public int Leto
        {
            get { return fLeto; }
            set { SetPropertyValue<int>("Leto", ref fLeto, value); }
        }
        decimal fPredlagateljT;
        public decimal PredlagateljT
        {
            get { return fPredlagateljT; }
            set { SetPropertyValue<decimal>("PredlagateljT", ref fPredlagateljT, value); }
        }
        decimal fRealizatorT;
        public decimal RealizatorT
        {
            get { return fRealizatorT; }
            set { SetPropertyValue<decimal>("RealizatorT", ref fRealizatorT, value); }
        }
        decimal fVsotaT;
        public decimal VsotaT
        {
            get { return fVsotaT; }
            set { SetPropertyValue<decimal>("VsotaT", ref fVsotaT, value); }
        }
        decimal fIzplaciloVMesecu;
        public decimal IzplaciloVMesecu
        {
            get { return fIzplaciloVMesecu; }
            set { SetPropertyValue<decimal>("IzplaciloVMesecu", ref fIzplaciloVMesecu, value); }
        }
        decimal fPrenosTvNaslednjiMesec;
        public decimal PrenosTvNaslednjiMesec
        {
            get { return fPrenosTvNaslednjiMesec; }
            set { SetPropertyValue<decimal>("PrenosTvNaslednjiMesec", ref fPrenosTvNaslednjiMesec, value); }
        }
        DateTime fDatumIzracuna;
        public DateTime DatumIzracuna
        {
            get { return fDatumIzracuna; }
            set { SetPropertyValue<DateTime>("DatumIzracuna", ref fDatumIzracuna, value); }
        }
        int fIDPrijave;
        public int IDPrijave
        {
            get { return fIDPrijave; }
            set { SetPropertyValue<int>("IDPrijave", ref fIDPrijave, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
        decimal fPrenosIzPrejsnjegaMeseca;
        public decimal PrenosIzPrejsnjegaMeseca
        {
            get { return fPrenosIzPrejsnjegaMeseca; }
            set { SetPropertyValue<decimal>("PrenosIzPrejsnjegaMeseca", ref fPrenosIzPrejsnjegaMeseca, value); }
        }
        string fImePriimek;
        [Size(150)]
        public string ImePriimek
        {
            get { return fImePriimek; }
            set { SetPropertyValue<string>("ImePriimek", ref fImePriimek, value); }
        }
        string fNotes;
        [Size(5000)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>("Notes", ref fNotes, value); }
        }
        string fOpomba;
        [Size(5000)]
        public string Opomba
        {
            get { return fOpomba; }
            set { SetPropertyValue<string>("Opomba", ref fOpomba, value); }
        }
        bool fSyncEmployee;
        public bool SyncEmployee
        {
            get { return fSyncEmployee; }
            set { SetPropertyValue<bool>("SyncEmployee", ref fSyncEmployee, value); }
        }
        DateTime fSyncDate;
        public DateTime SyncDate
        {
            get { return fSyncDate; }
            set { SetPropertyValue<DateTime>("SyncDate", ref fSyncDate, value); }
        }
        decimal fNePreneseneTocke;
        public decimal NePreneseneTocke
        {
            get { return fNePreneseneTocke; }
            set { SetPropertyValue<decimal>("NePreneseneTocke", ref fNePreneseneTocke, value); }
        }
    }

}
