//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class KVP_Status : XPLiteObject
    {
        int fidKVP_Status;
        [Key(true)]
        public int idKVP_Status
        {
            get { return fidKVP_Status; }
            set { SetPropertyValue<int>("idKVP_Status", ref fidKVP_Status, value); }
        }
        Status fidStatus;
        [Association(@"KVP_StatusReferencesStatus")]
        public Status idStatus
        {
            get { return fidStatus; }
            set { SetPropertyValue<Status>("idStatus", ref fidStatus, value); }
        }
        KVPDocument fidKVPDocument;
        [Association(@"KVP_StatusReferencesKVPDocument")]
        public KVPDocument idKVPDocument
        {
            get { return fidKVPDocument; }
            set { SetPropertyValue<KVPDocument>("idKVPDocument", ref fidKVPDocument, value); }
        }
        string fOpomba;
        [Size(5000)]
        public string Opomba
        {
            get { return fOpomba; }
            set { SetPropertyValue<string>("Opomba", ref fOpomba, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
        Users fIDPrijava;
        [Association(@"KVP_StatusReferencesUsers")]
        public Users IDPrijava
        {
            get { return fIDPrijava; }
            set { SetPropertyValue<Users>("IDPrijava", ref fIDPrijava, value); }
        }
    }

}
