//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class KVPDocument : XPLiteObject
    {
        int fidKVPDocument;
        [Key(true)]
        public int idKVPDocument
        {
            get { return fidKVPDocument; }
            set { SetPropertyValue<int>("idKVPDocument", ref fidKVPDocument, value); }
        }
        Tip fidTip;
        [Association(@"KVPDocumentReferencesTip")]
        public Tip idTip
        {
            get { return fidTip; }
            set { SetPropertyValue<Tip>("idTip", ref fidTip, value); }
        }
        Users fPredlagatelj;
        [Association(@"KVPDocumentReferencesUsers")]
        public Users Predlagatelj
        {
            get { return fPredlagatelj; }
            set { SetPropertyValue<Users>("Predlagatelj", ref fPredlagatelj, value); }
        }
        Users fRealizator;
        [Association(@"KVPDocumentReferencesUsers1")]
        public Users Realizator
        {
            get { return fRealizator; }
            set { SetPropertyValue<Users>("Realizator", ref fRealizator, value); }
        }
        TipRdeciKarton fidTipRdeciKarton;
        [Association(@"KVPDocumentReferencesTipRdeciKarton")]
        public TipRdeciKarton idTipRdeciKarton
        {
            get { return fidTipRdeciKarton; }
            set { SetPropertyValue<TipRdeciKarton>("idTipRdeciKarton", ref fidTipRdeciKarton, value); }
        }
        string fStevilkaKVP;
        [Size(50)]
        public string StevilkaKVP
        {
            get { return fStevilkaKVP; }
            set { SetPropertyValue<string>("StevilkaKVP", ref fStevilkaKVP, value); }
        }
        decimal fvodja_teama;
        public decimal vodja_teama
        {
            get { return fvodja_teama; }
            set { SetPropertyValue<decimal>("vodja_teama", ref fvodja_teama, value); }
        }
        string fOpisProblem;
        [Size(5000)]
        public string OpisProblem
        {
            get { return fOpisProblem; }
            set { SetPropertyValue<string>("OpisProblem", ref fOpisProblem, value); }
        }
        string fPredlogIzboljsave;
        [Size(5000)]
        public string PredlogIzboljsave
        {
            get { return fPredlogIzboljsave; }
            set { SetPropertyValue<string>("PredlogIzboljsave", ref fPredlogIzboljsave, value); }
        }
        string fPrihranekStroski;
        [Size(500)]
        public string PrihranekStroski
        {
            get { return fPrihranekStroski; }
            set { SetPropertyValue<string>("PrihranekStroski", ref fPrihranekStroski, value); }
        }
        string fAktivnostRK;
        [Size(5000)]
        public string AktivnostRK
        {
            get { return fAktivnostRK; }
            set { SetPropertyValue<string>("AktivnostRK", ref fAktivnostRK, value); }
        }
        string fPriloge;
        [Size(SizeAttribute.Unlimited)]
        public string Priloge
        {
            get { return fPriloge; }
            set { SetPropertyValue<string>("Priloge", ref fPriloge, value); }
        }
        DateTime fRokOdziva;
        public DateTime RokOdziva
        {
            get { return fRokOdziva; }
            set { SetPropertyValue<DateTime>("RokOdziva", ref fRokOdziva, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
        string fOpisLokacija;
        [Size(200)]
        public string OpisLokacija
        {
            get { return fOpisLokacija; }
            set { SetPropertyValue<string>("OpisLokacija", ref fOpisLokacija, value); }
        }
        string fOpisNapakeRK;
        [Size(5000)]
        public string OpisNapakeRK
        {
            get { return fOpisNapakeRK; }
            set { SetPropertyValue<string>("OpisNapakeRK", ref fOpisNapakeRK, value); }
        }
        DateTime fDatumVnosa;
        public DateTime DatumVnosa
        {
            get { return fDatumVnosa; }
            set { SetPropertyValue<DateTime>("DatumVnosa", ref fDatumVnosa, value); }
        }
        DateTime fDatumSpremembe;
        public DateTime DatumSpremembe
        {
            get { return fDatumSpremembe; }
            set { SetPropertyValue<DateTime>("DatumSpremembe", ref fDatumSpremembe, value); }
        }
        string fCIPOpombe;
        [Size(600)]
        public string CIPOpombe
        {
            get { return fCIPOpombe; }
            set { SetPropertyValue<string>("CIPOpombe", ref fCIPOpombe, value); }
        }
        string fStroj;
        [Size(200)]
        public string Stroj
        {
            get { return fStroj; }
            set { SetPropertyValue<string>("Stroj", ref fStroj, value); }
        }
        string fStrojStevilka;
        [Size(200)]
        public string StrojStevilka
        {
            get { return fStrojStevilka; }
            set { SetPropertyValue<string>("StrojStevilka", ref fStrojStevilka, value); }
        }
        string fLinija;
        [Size(200)]
        public string Linija
        {
            get { return fLinija; }
            set { SetPropertyValue<string>("Linija", ref fLinija, value); }
        }
        Status fLastStatusId;
        [Association(@"KVPDocumentReferencesStatus")]
        public Status LastStatusId
        {
            get { return fLastStatusId; }
            set { SetPropertyValue<Status>("LastStatusId", ref fLastStatusId, value); }
        }
        DateTime fDatumRealizacije;
        public DateTime DatumRealizacije
        {
            get { return fDatumRealizacije; }
            set { SetPropertyValue<DateTime>("DatumRealizacije", ref fDatumRealizacije, value); }
        }
        string fOpombeVodja;
        [Size(600)]
        public string OpombeVodja
        {
            get { return fOpombeVodja; }
            set { SetPropertyValue<string>("OpombeVodja", ref fOpombeVodja, value); }
        }
        string fZavrnitevOpis;
        [Size(600)]
        public string ZavrnitevOpis
        {
            get { return fZavrnitevOpis; }
            set { SetPropertyValue<string>("ZavrnitevOpis", ref fZavrnitevOpis, value); }
        }
        Users fZavrnitevIdUser;
        [Association(@"KVPDocumentReferencesUsers4")]
        public Users ZavrnitevIdUser
        {
            get { return fZavrnitevIdUser; }
            set { SetPropertyValue<Users>("ZavrnitevIdUser", ref fZavrnitevIdUser, value); }
        }
        bool fPrihranekStroskiDA_NE;
        public bool PrihranekStroskiDA_NE
        {
            get { return fPrihranekStroskiDA_NE; }
            set { SetPropertyValue<bool>("PrihranekStroskiDA_NE", ref fPrihranekStroskiDA_NE, value); }
        }
        Users fObvescenaOsebaZavrnitve;
        [Association(@"KVPDocumentReferencesUsers3")]
        public Users ObvescenaOsebaZavrnitve
        {
            get { return fObvescenaOsebaZavrnitve; }
            set { SetPropertyValue<Users>("ObvescenaOsebaZavrnitve", ref fObvescenaOsebaZavrnitve, value); }
        }
        int fIDPrijave;
        public int IDPrijave
        {
            get { return fIDPrijave; }
            set { SetPropertyValue<int>("IDPrijave", ref fIDPrijave, value); }
        }
        KVPSkupina fKVPSkupinaID;
        [Association(@"KVPDocumentReferencesKVPSkupina")]
        public KVPSkupina KVPSkupinaID
        {
            get { return fKVPSkupinaID; }
            set { SetPropertyValue<KVPSkupina>("KVPSkupinaID", ref fKVPSkupinaID, value); }
        }
        int fZaporednaStevilka;
        public int ZaporednaStevilka
        {
            get { return fZaporednaStevilka; }
            set { SetPropertyValue<int>("ZaporednaStevilka", ref fZaporednaStevilka, value); }
        }
        Lokacija fLokacijaID;
        [Association(@"KVPDocumentReferencesLokacija")]
        public Lokacija LokacijaID
        {
            get { return fLokacijaID; }
            set { SetPropertyValue<Lokacija>("LokacijaID", ref fLokacijaID, value); }
        }
        Linija fLinijaID;
        [Association(@"KVPDocumentReferencesLinija")]
        public Linija LinijaID
        {
            get { return fLinijaID; }
            set { SetPropertyValue<Linija>("LinijaID", ref fLinijaID, value); }
        }
        Stroj fStrojID;
        [Association(@"KVPDocumentReferencesStroj")]
        public Stroj StrojID
        {
            get { return fStrojID; }
            set { SetPropertyValue<Stroj>("StrojID", ref fStrojID, value); }
        }
        Users fLastPresojaID;
        [Association(@"KVPDocumentReferencesUsers2")]
        public Users LastPresojaID
        {
            get { return fLastPresojaID; }
            set { SetPropertyValue<Users>("LastPresojaID", ref fLastPresojaID, value); }
        }
        DateTime fDatumZakljuceneIdeje;
        public DateTime DatumZakljuceneIdeje
        {
            get { return fDatumZakljuceneIdeje; }
            set { SetPropertyValue<DateTime>("DatumZakljuceneIdeje", ref fDatumZakljuceneIdeje, value); }
        }
        bool fVarnostRK;
        public bool VarnostRK
        {
            get { return fVarnostRK; }
            set { SetPropertyValue<bool>("VarnostRK", ref fVarnostRK, value); }
        }
        DateTime fDatumPoslanePosteZaVarnost;
        public DateTime DatumPoslanePosteZaVarnost
        {
            get { return fDatumPoslanePosteZaVarnost; }
            set { SetPropertyValue<DateTime>("DatumPoslanePosteZaVarnost", ref fDatumPoslanePosteZaVarnost, value); }
        }
        bool fPrenosRKizKVP;
        public bool PrenosRKizKVP
        {
            get { return fPrenosRKizKVP; }
            set { SetPropertyValue<bool>("PrenosRKizKVP", ref fPrenosRKizKVP, value); }
        }
        Users fRKVnesel;
        [Association(@"KVPDocumentReferencesUsers5")]
        public Users RKVnesel
        {
            get { return fRKVnesel; }
            set { SetPropertyValue<Users>("RKVnesel", ref fRKVnesel, value); }
        }
        [Association(@"KVP_StatusReferencesKVPDocument")]
        public XPCollection<KVP_Status> KVP_Statuss { get { return GetCollection<KVP_Status>("KVP_Statuss"); } }
        [Association(@"KVPPresojeReferencesKVPDocument")]
        public XPCollection<KVPPresoje> KVPPresojes { get { return GetCollection<KVPPresoje>("KVPPresojes"); } }
        [Association(@"KVPKomentarjiReferencesKVPDocument")]
        public XPCollection<KVPKomentarji> KVPKomentarjis { get { return GetCollection<KVPKomentarji>("KVPKomentarjis"); } }
    }

}
