//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class KVPExcell : XPLiteObject
    {
        double fLeto;
        public double Leto
        {
            get { return fLeto; }
            set { SetPropertyValue<double>("Leto", ref fLeto, value); }
        }
        double fMesec;
        public double Mesec
        {
            get { return fMesec; }
            set { SetPropertyValue<double>("Mesec", ref fMesec, value); }
        }
        double fZaporedna_številka;
        [Persistent(@"Zaporedna _številka")]
        public double Zaporedna_številka
        {
            get { return fZaporedna_številka; }
            set { SetPropertyValue<double>("Zaporedna_številka", ref fZaporedna_številka, value); }
        }
        string fšt_KVP;
        [Size(255)]
        [Persistent(@"št# KVP")]
        public string št_KVP
        {
            get { return fšt_KVP; }
            set { SetPropertyValue<string>("št_KVP", ref fšt_KVP, value); }
        }
        string fKVPskupina;
        [Size(255)]
        [Persistent(@"KVP skupina")]
        public string KVPskupina
        {
            get { return fKVPskupina; }
            set { SetPropertyValue<string>("KVPskupina", ref fKVPskupina, value); }
        }
        DateTime fdatumvnosa;
        [Persistent(@"datum vnosa")]
        public DateTime datumvnosa
        {
            get { return fdatumvnosa; }
            set { SetPropertyValue<DateTime>("datumvnosa", ref fdatumvnosa, value); }
        }
        string fUporabnik;
        [Size(255)]
        public string Uporabnik
        {
            get { return fUporabnik; }
            set { SetPropertyValue<string>("Uporabnik", ref fUporabnik, value); }
        }
        string fopisKVPideje;
        [Size(3000)]
        [Persistent(@"opis KVP ideje")]
        public string opisKVPideje
        {
            get { return fopisKVPideje; }
            set { SetPropertyValue<string>("opisKVPideje", ref fopisKVPideje, value); }
        }
        string fVodjazaodobritevideje;
        [Size(255)]
        [Persistent(@"Vodja za odobritev ideje")]
        public string Vodjazaodobritevideje
        {
            get { return fVodjazaodobritevideje; }
            set { SetPropertyValue<string>("Vodjazaodobritevideje", ref fVodjazaodobritevideje, value); }
        }
        string fPresoja;
        [Size(255)]
        public string Presoja
        {
            get { return fPresoja; }
            set { SetPropertyValue<string>("Presoja", ref fPresoja, value); }
        }
        string fRealizator;
        [Size(255)]
        public string Realizator
        {
            get { return fRealizator; }
            set { SetPropertyValue<string>("Realizator", ref fRealizator, value); }
        }
        DateTime fDatumzaključeneideje;
        [Persistent(@"Datum zaključene ideje")]
        public DateTime Datumzaključeneideje
        {
            get { return fDatumzaključeneideje; }
            set { SetPropertyValue<DateTime>("Datumzaključeneideje", ref fDatumzaključeneideje, value); }
        }
        double fSprejel;
        public double Sprejel
        {
            get { return fSprejel; }
            set { SetPropertyValue<double>("Sprejel", ref fSprejel, value); }
        }
        double fZavrnil;
        public double Zavrnil
        {
            get { return fZavrnil; }
            set { SetPropertyValue<double>("Zavrnil", ref fZavrnil, value); }
        }
        string fRealiziral;
        [Size(255)]
        public string Realiziral
        {
            get { return fRealiziral; }
            set { SetPropertyValue<string>("Realiziral", ref fRealiziral, value); }
        }
        string fopombe;
        [Size(255)]
        public string opombe
        {
            get { return fopombe; }
            set { SetPropertyValue<string>("opombe", ref fopombe, value); }
        }
        double fČASDOGOTOVEIDEJE;
        [Persistent(@"ČAS DO GOTOVE IDEJE")]
        public double ČASDOGOTOVEIDEJE
        {
            get { return fČASDOGOTOVEIDEJE; }
            set { SetPropertyValue<double>("ČASDOGOTOVEIDEJE", ref fČASDOGOTOVEIDEJE, value); }
        }
        string fSkupina;
        [Size(255)]
        public string Skupina
        {
            get { return fSkupina; }
            set { SetPropertyValue<string>("Skupina", ref fSkupina, value); }
        }
        string fTipideje;
        [Size(255)]
        [Persistent(@"Tip ideje")]
        public string Tipideje
        {
            get { return fTipideje; }
            set { SetPropertyValue<string>("Tipideje", ref fTipideje, value); }
        }
        string fTočkepredlagatelj;
        [Size(255)]
        [Persistent(@"Točke predlagatelj")]
        public string Točkepredlagatelj
        {
            get { return fTočkepredlagatelj; }
            set { SetPropertyValue<string>("Točkepredlagatelj", ref fTočkepredlagatelj, value); }
        }
        string fTočkeRealizator;
        [Size(255)]
        [Persistent(@"Točke Realizator")]
        public string TočkeRealizator
        {
            get { return fTočkeRealizator; }
            set { SetPropertyValue<string>("TočkeRealizator", ref fTočkeRealizator, value); }
        }
        double fIDzaposlenega;
        [Persistent(@"ID zaposlenega")]
        public double IDzaposlenega
        {
            get { return fIDzaposlenega; }
            set { SetPropertyValue<double>("IDzaposlenega", ref fIDzaposlenega, value); }
        }
        string fCIP_Prihranek___;
        [Size(300)]
        [Persistent(@"CIP_Prihranek (€)")]
        public string CIP_Prihranek___
        {
            get { return fCIP_Prihranek___; }
            set { SetPropertyValue<string>("CIP_Prihranek___", ref fCIP_Prihranek___, value); }
        }
        double fLeto1;
        public double Leto1
        {
            get { return fLeto1; }
            set { SetPropertyValue<double>("Leto1", ref fLeto1, value); }
        }
        double fMesec1;
        public double Mesec1
        {
            get { return fMesec1; }
            set { SetPropertyValue<double>("Mesec1", ref fMesec1, value); }
        }
        string fIzplačiloTočk;
        [Size(255)]
        [Persistent(@"Izplačilo Točk")]
        public string IzplačiloTočk
        {
            get { return fIzplačiloTočk; }
            set { SetPropertyValue<string>("IzplačiloTočk", ref fIzplačiloTočk, value); }
        }
        double fSifraPredlagatelja;
        public double SifraPredlagatelja
        {
            get { return fSifraPredlagatelja; }
            set { SetPropertyValue<double>("SifraPredlagatelja", ref fSifraPredlagatelja, value); }
        }
        double fSifraRealizatorja;
        public double SifraRealizatorja
        {
            get { return fSifraRealizatorja; }
            set { SetPropertyValue<double>("SifraRealizatorja", ref fSifraRealizatorja, value); }
        }
        string fF29;
        [Size(255)]
        public string F29
        {
            get { return fF29; }
            set { SetPropertyValue<string>("F29", ref fF29, value); }
        }
        string fF30;
        [Size(255)]
        public string F30
        {
            get { return fF30; }
            set { SetPropertyValue<string>("F30", ref fF30, value); }
        }
        string fF31;
        [Size(255)]
        public string F31
        {
            get { return fF31; }
            set { SetPropertyValue<string>("F31", ref fF31, value); }
        }
        string fF32;
        [Size(255)]
        public string F32
        {
            get { return fF32; }
            set { SetPropertyValue<string>("F32", ref fF32, value); }
        }
        string fF33;
        [Size(255)]
        public string F33
        {
            get { return fF33; }
            set { SetPropertyValue<string>("F33", ref fF33, value); }
        }
        double fF34;
        public double F34
        {
            get { return fF34; }
            set { SetPropertyValue<double>("F34", ref fF34, value); }
        }
        string fF35;
        [Size(255)]
        public string F35
        {
            get { return fF35; }
            set { SetPropertyValue<string>("F35", ref fF35, value); }
        }
        int fIDKVPExcell;
        [Key]
        public int IDKVPExcell
        {
            get { return fIDKVPExcell; }
            set { SetPropertyValue<int>("IDKVPExcell", ref fIDKVPExcell, value); }
        }
        int fInsertedDB;
        public int InsertedDB
        {
            get { return fInsertedDB; }
            set { SetPropertyValue<int>("InsertedDB", ref fInsertedDB, value); }
        }
    }

}
