//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class KVPExellDoc : XPLiteObject
    {
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fLeto;
        [Size(255)]
        public string Leto
        {
            get { return fLeto; }
            set { SetPropertyValue<string>("Leto", ref fLeto, value); }
        }
        string fMesec;
        [Size(255)]
        public string Mesec
        {
            get { return fMesec; }
            set { SetPropertyValue<string>("Mesec", ref fMesec, value); }
        }
        string fZaporedna_številka;
        [Size(255)]
        [Persistent(@"Zaporedna _številka")]
        public string Zaporedna_številka
        {
            get { return fZaporedna_številka; }
            set { SetPropertyValue<string>("Zaporedna_številka", ref fZaporedna_številka, value); }
        }
        string fšt_KVP;
        [Size(255)]
        [Persistent(@" št# KVP ")]
        public string št_KVP
        {
            get { return fšt_KVP; }
            set { SetPropertyValue<string>("št_KVP", ref fšt_KVP, value); }
        }
        string fKVPskupina;
        [Size(255)]
        [Persistent(@"KVP skupina")]
        public string KVPskupina
        {
            get { return fKVPskupina; }
            set { SetPropertyValue<string>("KVPskupina", ref fKVPskupina, value); }
        }
        string fdatumvnosa;
        [Size(255)]
        [Persistent(@"datum vnosa")]
        public string datumvnosa
        {
            get { return fdatumvnosa; }
            set { SetPropertyValue<string>("datumvnosa", ref fdatumvnosa, value); }
        }
        string fUporabnik;
        [Size(255)]
        public string Uporabnik
        {
            get { return fUporabnik; }
            set { SetPropertyValue<string>("Uporabnik", ref fUporabnik, value); }
        }
        string fopisKVPideje;
        [Size(3000)]
        [Persistent(@"opis KVP ideje")]
        public string opisKVPideje
        {
            get { return fopisKVPideje; }
            set { SetPropertyValue<string>("opisKVPideje", ref fopisKVPideje, value); }
        }
        string fVodjazaodobritevideje;
        [Size(255)]
        [Persistent(@"Vodja za odobritev ideje")]
        public string Vodjazaodobritevideje
        {
            get { return fVodjazaodobritevideje; }
            set { SetPropertyValue<string>("Vodjazaodobritevideje", ref fVodjazaodobritevideje, value); }
        }
        string fPresoja;
        [Size(255)]
        public string Presoja
        {
            get { return fPresoja; }
            set { SetPropertyValue<string>("Presoja", ref fPresoja, value); }
        }
        string fRealizator;
        [Size(255)]
        public string Realizator
        {
            get { return fRealizator; }
            set { SetPropertyValue<string>("Realizator", ref fRealizator, value); }
        }
        string fDatumzaključeneideje;
        [Size(255)]
        [Persistent(@"Datum zaključene ideje")]
        public string Datumzaključeneideje
        {
            get { return fDatumzaključeneideje; }
            set { SetPropertyValue<string>("Datumzaključeneideje", ref fDatumzaključeneideje, value); }
        }
        string fSprejel;
        [Size(255)]
        public string Sprejel
        {
            get { return fSprejel; }
            set { SetPropertyValue<string>("Sprejel", ref fSprejel, value); }
        }
        string fZavrnil;
        [Size(255)]
        public string Zavrnil
        {
            get { return fZavrnil; }
            set { SetPropertyValue<string>("Zavrnil", ref fZavrnil, value); }
        }
        string fRealiziral;
        [Size(255)]
        public string Realiziral
        {
            get { return fRealiziral; }
            set { SetPropertyValue<string>("Realiziral", ref fRealiziral, value); }
        }
        string fopombe;
        [Size(3000)]
        public string opombe
        {
            get { return fopombe; }
            set { SetPropertyValue<string>("opombe", ref fopombe, value); }
        }
        string fČASDOGOTOVEIDEJE;
        [Size(255)]
        [Persistent(@"ČAS DO GOTOVE IDEJE")]
        public string ČASDOGOTOVEIDEJE
        {
            get { return fČASDOGOTOVEIDEJE; }
            set { SetPropertyValue<string>("ČASDOGOTOVEIDEJE", ref fČASDOGOTOVEIDEJE, value); }
        }
        string fSkupina;
        [Size(255)]
        public string Skupina
        {
            get { return fSkupina; }
            set { SetPropertyValue<string>("Skupina", ref fSkupina, value); }
        }
        string fTipideje;
        [Size(255)]
        [Persistent(@"Tip ideje")]
        public string Tipideje
        {
            get { return fTipideje; }
            set { SetPropertyValue<string>("Tipideje", ref fTipideje, value); }
        }
        string fTočkepredlagatelj;
        [Size(255)]
        [Persistent(@"Točke predlagatelj")]
        public string Točkepredlagatelj
        {
            get { return fTočkepredlagatelj; }
            set { SetPropertyValue<string>("Točkepredlagatelj", ref fTočkepredlagatelj, value); }
        }
        string fTočkeRealizator;
        [Size(255)]
        [Persistent(@"Točke Realizator")]
        public string TočkeRealizator
        {
            get { return fTočkeRealizator; }
            set { SetPropertyValue<string>("TočkeRealizator", ref fTočkeRealizator, value); }
        }
        string fIDzaposlenega;
        [Size(255)]
        [Persistent(@"ID zaposlenega")]
        public string IDzaposlenega
        {
            get { return fIDzaposlenega; }
            set { SetPropertyValue<string>("IDzaposlenega", ref fIDzaposlenega, value); }
        }
        string fCIP_Prihranek___;
        [Size(255)]
        [Persistent(@"CIP_Prihranek (€)")]
        public string CIP_Prihranek___
        {
            get { return fCIP_Prihranek___; }
            set { SetPropertyValue<string>("CIP_Prihranek___", ref fCIP_Prihranek___, value); }
        }
        string fLeto1;
        [Size(255)]
        public string Leto1
        {
            get { return fLeto1; }
            set { SetPropertyValue<string>("Leto1", ref fLeto1, value); }
        }
        string fMesec1;
        [Size(255)]
        public string Mesec1
        {
            get { return fMesec1; }
            set { SetPropertyValue<string>("Mesec1", ref fMesec1, value); }
        }
        string fIzplačiloTočk;
        [Size(255)]
        [Persistent(@"Izplačilo Točk")]
        public string IzplačiloTočk
        {
            get { return fIzplačiloTočk; }
            set { SetPropertyValue<string>("IzplačiloTočk", ref fIzplačiloTočk, value); }
        }
        string fŠifrapredlagatelja;
        [Size(255)]
        [Persistent(@"Šifra predlagatelja")]
        public string Šifrapredlagatelja
        {
            get { return fŠifrapredlagatelja; }
            set { SetPropertyValue<string>("Šifrapredlagatelja", ref fŠifrapredlagatelja, value); }
        }
        string fŠifrarealizator;
        [Size(255)]
        [Persistent(@"Šifra realizator")]
        public string Šifrarealizator
        {
            get { return fŠifrarealizator; }
            set { SetPropertyValue<string>("Šifrarealizator", ref fŠifrarealizator, value); }
        }
    }

}
