//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class KVPUvoz15_12 : XPLiteObject
    {
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fLeto;
        [Size(255)]
        public string Leto
        {
            get { return fLeto; }
            set { SetPropertyValue<string>("Leto", ref fLeto, value); }
        }
        string fMesec;
        [Size(255)]
        public string Mesec
        {
            get { return fMesec; }
            set { SetPropertyValue<string>("Mesec", ref fMesec, value); }
        }
        string fZapStev;
        [Size(255)]
        public string ZapStev
        {
            get { return fZapStev; }
            set { SetPropertyValue<string>("ZapStev", ref fZapStev, value); }
        }
        string fStKVP;
        [Size(255)]
        [Persistent(@"StKVP ")]
        public string StKVP
        {
            get { return fStKVP; }
            set { SetPropertyValue<string>("StKVP", ref fStKVP, value); }
        }
        string fKVPskupina;
        [Size(255)]
        public string KVPskupina
        {
            get { return fKVPskupina; }
            set { SetPropertyValue<string>("KVPskupina", ref fKVPskupina, value); }
        }
        DateTime fDatumVnosa;
        public DateTime DatumVnosa
        {
            get { return fDatumVnosa; }
            set { SetPropertyValue<DateTime>("DatumVnosa", ref fDatumVnosa, value); }
        }
        string fUporabnik;
        [Size(255)]
        public string Uporabnik
        {
            get { return fUporabnik; }
            set { SetPropertyValue<string>("Uporabnik", ref fUporabnik, value); }
        }
        string fOpisKVPIdeje;
        [Size(4000)]
        public string OpisKVPIdeje
        {
            get { return fOpisKVPIdeje; }
            set { SetPropertyValue<string>("OpisKVPIdeje", ref fOpisKVPIdeje, value); }
        }
        string fVodjaZaOdobritevIdeje;
        [Size(255)]
        public string VodjaZaOdobritevIdeje
        {
            get { return fVodjaZaOdobritevIdeje; }
            set { SetPropertyValue<string>("VodjaZaOdobritevIdeje", ref fVodjaZaOdobritevIdeje, value); }
        }
        string fPresoja;
        [Size(255)]
        public string Presoja
        {
            get { return fPresoja; }
            set { SetPropertyValue<string>("Presoja", ref fPresoja, value); }
        }
        string fRealizator;
        [Size(255)]
        public string Realizator
        {
            get { return fRealizator; }
            set { SetPropertyValue<string>("Realizator", ref fRealizator, value); }
        }
        DateTime fDatumZakljuceneIdeje;
        public DateTime DatumZakljuceneIdeje
        {
            get { return fDatumZakljuceneIdeje; }
            set { SetPropertyValue<DateTime>("DatumZakljuceneIdeje", ref fDatumZakljuceneIdeje, value); }
        }
        int fSprejel;
        public int Sprejel
        {
            get { return fSprejel; }
            set { SetPropertyValue<int>("Sprejel", ref fSprejel, value); }
        }
        int fZavrnil;
        public int Zavrnil
        {
            get { return fZavrnil; }
            set { SetPropertyValue<int>("Zavrnil", ref fZavrnil, value); }
        }
        int fRealiziral;
        public int Realiziral
        {
            get { return fRealiziral; }
            set { SetPropertyValue<int>("Realiziral", ref fRealiziral, value); }
        }
        string fOpombe;
        [Size(4000)]
        public string Opombe
        {
            get { return fOpombe; }
            set { SetPropertyValue<string>("Opombe", ref fOpombe, value); }
        }
        string fCasDoGotoveIdeje;
        [Size(255)]
        public string CasDoGotoveIdeje
        {
            get { return fCasDoGotoveIdeje; }
            set { SetPropertyValue<string>("CasDoGotoveIdeje", ref fCasDoGotoveIdeje, value); }
        }
        string fSkupina;
        [Size(255)]
        public string Skupina
        {
            get { return fSkupina; }
            set { SetPropertyValue<string>("Skupina", ref fSkupina, value); }
        }
        string fTipIdeje;
        [Size(255)]
        public string TipIdeje
        {
            get { return fTipIdeje; }
            set { SetPropertyValue<string>("TipIdeje", ref fTipIdeje, value); }
        }
        string fTockePredlagatelj;
        [Size(255)]
        public string TockePredlagatelj
        {
            get { return fTockePredlagatelj; }
            set { SetPropertyValue<string>("TockePredlagatelj", ref fTockePredlagatelj, value); }
        }
        string fTockeRealizator;
        [Size(255)]
        public string TockeRealizator
        {
            get { return fTockeRealizator; }
            set { SetPropertyValue<string>("TockeRealizator", ref fTockeRealizator, value); }
        }
        string fIDZaposlenega;
        [Size(255)]
        public string IDZaposlenega
        {
            get { return fIDZaposlenega; }
            set { SetPropertyValue<string>("IDZaposlenega", ref fIDZaposlenega, value); }
        }
        string fCIPPrihranek;
        [Size(255)]
        public string CIPPrihranek
        {
            get { return fCIPPrihranek; }
            set { SetPropertyValue<string>("CIPPrihranek", ref fCIPPrihranek, value); }
        }
        string fLeto1;
        [Size(255)]
        public string Leto1
        {
            get { return fLeto1; }
            set { SetPropertyValue<string>("Leto1", ref fLeto1, value); }
        }
        string fMesec1;
        [Size(255)]
        public string Mesec1
        {
            get { return fMesec1; }
            set { SetPropertyValue<string>("Mesec1", ref fMesec1, value); }
        }
        string fIzplaciloTock;
        [Size(255)]
        public string IzplaciloTock
        {
            get { return fIzplaciloTock; }
            set { SetPropertyValue<string>("IzplaciloTock", ref fIzplaciloTock, value); }
        }
        string fSifraPredlagatelja;
        [Size(255)]
        public string SifraPredlagatelja
        {
            get { return fSifraPredlagatelja; }
            set { SetPropertyValue<string>("SifraPredlagatelja", ref fSifraPredlagatelja, value); }
        }
        string fSifraRealizator;
        [Size(255)]
        public string SifraRealizator
        {
            get { return fSifraRealizator; }
            set { SetPropertyValue<string>("SifraRealizator", ref fSifraRealizator, value); }
        }
        int fInsertedDB;
        public int InsertedDB
        {
            get { return fInsertedDB; }
            set { SetPropertyValue<int>("InsertedDB", ref fInsertedDB, value); }
        }
    }

}
