//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class PlanRealizacija : XPLiteObject
    {
        int fidPlanRealizacija;
        [Key(true)]
        public int idPlanRealizacija
        {
            get { return fidPlanRealizacija; }
            set { SetPropertyValue<int>("idPlanRealizacija", ref fidPlanRealizacija, value); }
        }
        KVPSkupina fidKVPSkupina;
        [Association(@"PlanRealizacijaReferencesKVPSkupina")]
        public KVPSkupina idKVPSkupina
        {
            get { return fidKVPSkupina; }
            set { SetPropertyValue<KVPSkupina>("idKVPSkupina", ref fidKVPSkupina, value); }
        }
        int fLeto;
        public int Leto
        {
            get { return fLeto; }
            set { SetPropertyValue<int>("Leto", ref fLeto, value); }
        }
        decimal fPlan_Jan;
        public decimal Plan_Jan
        {
            get { return fPlan_Jan; }
            set { SetPropertyValue<decimal>("Plan_Jan", ref fPlan_Jan, value); }
        }
        decimal fReal_Jan;
        public decimal Real_Jan
        {
            get { return fReal_Jan; }
            set { SetPropertyValue<decimal>("Real_Jan", ref fReal_Jan, value); }
        }
        decimal fOdst_Jan;
        public decimal Odst_Jan
        {
            get { return fOdst_Jan; }
            set { SetPropertyValue<decimal>("Odst_Jan", ref fOdst_Jan, value); }
        }
        decimal fPlan_Feb;
        public decimal Plan_Feb
        {
            get { return fPlan_Feb; }
            set { SetPropertyValue<decimal>("Plan_Feb", ref fPlan_Feb, value); }
        }
        decimal fReal_Feb;
        public decimal Real_Feb
        {
            get { return fReal_Feb; }
            set { SetPropertyValue<decimal>("Real_Feb", ref fReal_Feb, value); }
        }
        decimal fOdst_Feb;
        public decimal Odst_Feb
        {
            get { return fOdst_Feb; }
            set { SetPropertyValue<decimal>("Odst_Feb", ref fOdst_Feb, value); }
        }
        decimal fPlan_Mar;
        public decimal Plan_Mar
        {
            get { return fPlan_Mar; }
            set { SetPropertyValue<decimal>("Plan_Mar", ref fPlan_Mar, value); }
        }
        decimal fReal_Mar;
        public decimal Real_Mar
        {
            get { return fReal_Mar; }
            set { SetPropertyValue<decimal>("Real_Mar", ref fReal_Mar, value); }
        }
        decimal fOdst_Mar;
        public decimal Odst_Mar
        {
            get { return fOdst_Mar; }
            set { SetPropertyValue<decimal>("Odst_Mar", ref fOdst_Mar, value); }
        }
        decimal fPlan_Apr;
        public decimal Plan_Apr
        {
            get { return fPlan_Apr; }
            set { SetPropertyValue<decimal>("Plan_Apr", ref fPlan_Apr, value); }
        }
        decimal fReal_Apr;
        public decimal Real_Apr
        {
            get { return fReal_Apr; }
            set { SetPropertyValue<decimal>("Real_Apr", ref fReal_Apr, value); }
        }
        decimal fOdst_Apr;
        public decimal Odst_Apr
        {
            get { return fOdst_Apr; }
            set { SetPropertyValue<decimal>("Odst_Apr", ref fOdst_Apr, value); }
        }
        decimal fPlan_Maj;
        public decimal Plan_Maj
        {
            get { return fPlan_Maj; }
            set { SetPropertyValue<decimal>("Plan_Maj", ref fPlan_Maj, value); }
        }
        decimal fReal_Maj;
        public decimal Real_Maj
        {
            get { return fReal_Maj; }
            set { SetPropertyValue<decimal>("Real_Maj", ref fReal_Maj, value); }
        }
        decimal fOdst_Maj;
        public decimal Odst_Maj
        {
            get { return fOdst_Maj; }
            set { SetPropertyValue<decimal>("Odst_Maj", ref fOdst_Maj, value); }
        }
        decimal fPlan_Jun;
        public decimal Plan_Jun
        {
            get { return fPlan_Jun; }
            set { SetPropertyValue<decimal>("Plan_Jun", ref fPlan_Jun, value); }
        }
        decimal fReal_Jun;
        public decimal Real_Jun
        {
            get { return fReal_Jun; }
            set { SetPropertyValue<decimal>("Real_Jun", ref fReal_Jun, value); }
        }
        decimal fOdst_Jun;
        public decimal Odst_Jun
        {
            get { return fOdst_Jun; }
            set { SetPropertyValue<decimal>("Odst_Jun", ref fOdst_Jun, value); }
        }
        decimal fPlan_Jul;
        public decimal Plan_Jul
        {
            get { return fPlan_Jul; }
            set { SetPropertyValue<decimal>("Plan_Jul", ref fPlan_Jul, value); }
        }
        decimal fReal_Jul;
        public decimal Real_Jul
        {
            get { return fReal_Jul; }
            set { SetPropertyValue<decimal>("Real_Jul", ref fReal_Jul, value); }
        }
        decimal fOdst_Jul;
        public decimal Odst_Jul
        {
            get { return fOdst_Jul; }
            set { SetPropertyValue<decimal>("Odst_Jul", ref fOdst_Jul, value); }
        }
        decimal fPlan_Avg;
        public decimal Plan_Avg
        {
            get { return fPlan_Avg; }
            set { SetPropertyValue<decimal>("Plan_Avg", ref fPlan_Avg, value); }
        }
        decimal fReal_Avg;
        public decimal Real_Avg
        {
            get { return fReal_Avg; }
            set { SetPropertyValue<decimal>("Real_Avg", ref fReal_Avg, value); }
        }
        decimal fOdst_Avg;
        public decimal Odst_Avg
        {
            get { return fOdst_Avg; }
            set { SetPropertyValue<decimal>("Odst_Avg", ref fOdst_Avg, value); }
        }
        decimal fPlan_Sep;
        public decimal Plan_Sep
        {
            get { return fPlan_Sep; }
            set { SetPropertyValue<decimal>("Plan_Sep", ref fPlan_Sep, value); }
        }
        decimal fReal_Sep;
        public decimal Real_Sep
        {
            get { return fReal_Sep; }
            set { SetPropertyValue<decimal>("Real_Sep", ref fReal_Sep, value); }
        }
        decimal fOdst_Sep;
        public decimal Odst_Sep
        {
            get { return fOdst_Sep; }
            set { SetPropertyValue<decimal>("Odst_Sep", ref fOdst_Sep, value); }
        }
        decimal fPlan_Okt;
        public decimal Plan_Okt
        {
            get { return fPlan_Okt; }
            set { SetPropertyValue<decimal>("Plan_Okt", ref fPlan_Okt, value); }
        }
        decimal fReal_Okt;
        public decimal Real_Okt
        {
            get { return fReal_Okt; }
            set { SetPropertyValue<decimal>("Real_Okt", ref fReal_Okt, value); }
        }
        decimal fOdst_Okt;
        public decimal Odst_Okt
        {
            get { return fOdst_Okt; }
            set { SetPropertyValue<decimal>("Odst_Okt", ref fOdst_Okt, value); }
        }
        decimal fPlan_Nov;
        public decimal Plan_Nov
        {
            get { return fPlan_Nov; }
            set { SetPropertyValue<decimal>("Plan_Nov", ref fPlan_Nov, value); }
        }
        decimal fReal_Nov;
        public decimal Real_Nov
        {
            get { return fReal_Nov; }
            set { SetPropertyValue<decimal>("Real_Nov", ref fReal_Nov, value); }
        }
        decimal fOdst_Nov;
        public decimal Odst_Nov
        {
            get { return fOdst_Nov; }
            set { SetPropertyValue<decimal>("Odst_Nov", ref fOdst_Nov, value); }
        }
        decimal fPlan_Dec;
        public decimal Plan_Dec
        {
            get { return fPlan_Dec; }
            set { SetPropertyValue<decimal>("Plan_Dec", ref fPlan_Dec, value); }
        }
        decimal fReal_Dec;
        public decimal Real_Dec
        {
            get { return fReal_Dec; }
            set { SetPropertyValue<decimal>("Real_Dec", ref fReal_Dec, value); }
        }
        decimal fOdst_Dec;
        public decimal Odst_Dec
        {
            get { return fOdst_Dec; }
            set { SetPropertyValue<decimal>("Odst_Dec", ref fOdst_Dec, value); }
        }
        int fidVnos;
        public int idVnos
        {
            get { return fidVnos; }
            set { SetPropertyValue<int>("idVnos", ref fidVnos, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
    }

}
