//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class Status : XPLiteObject
    {
        int fidStatus;
        [Key(true)]
        public int idStatus
        {
            get { return fidStatus; }
            set { SetPropertyValue<int>("idStatus", ref fidStatus, value); }
        }
        string fKoda;
        [Size(30)]
        public string Koda
        {
            get { return fKoda; }
            set { SetPropertyValue<string>("Koda", ref fKoda, value); }
        }
        string fNaziv;
        public string Naziv
        {
            get { return fNaziv; }
            set { SetPropertyValue<string>("Naziv", ref fNaziv, value); }
        }
        bool fSamoRK;
        public bool SamoRK
        {
            get { return fSamoRK; }
            set { SetPropertyValue<bool>("SamoRK", ref fSamoRK, value); }
        }
        [Association(@"KVP_StatusReferencesStatus")]
        public XPCollection<KVP_Status> KVP_Statuss { get { return GetCollection<KVP_Status>("KVP_Statuss"); } }
        [Association(@"KVPDocumentReferencesStatus")]
        public XPCollection<KVPDocument> KVPDocuments { get { return GetCollection<KVPDocument>("KVPDocuments"); } }
    }

}
