//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class Tip : XPLiteObject
    {
        int fidTip;
        [Key(true)]
        public int idTip
        {
            get { return fidTip; }
            set { SetPropertyValue<int>("idTip", ref fidTip, value); }
        }
        string fNaziv;
        [Size(50)]
        public string Naziv
        {
            get { return fNaziv; }
            set { SetPropertyValue<string>("Naziv", ref fNaziv, value); }
        }
        decimal fTockeRealizator;
        public decimal TockeRealizator
        {
            get { return fTockeRealizator; }
            set { SetPropertyValue<decimal>("TockeRealizator", ref fTockeRealizator, value); }
        }
        decimal fTockePredlagatelj;
        public decimal TockePredlagatelj
        {
            get { return fTockePredlagatelj; }
            set { SetPropertyValue<decimal>("TockePredlagatelj", ref fTockePredlagatelj, value); }
        }
        string fKoda;
        [Size(10)]
        public string Koda
        {
            get { return fKoda; }
            set { SetPropertyValue<string>("Koda", ref fKoda, value); }
        }
        int fIDPrijave;
        public int IDPrijave
        {
            get { return fIDPrijave; }
            set { SetPropertyValue<int>("IDPrijave", ref fIDPrijave, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
        [Association(@"KVPDocumentReferencesTip")]
        public XPCollection<KVPDocument> KVPDocuments { get { return GetCollection<KVPDocument>("KVPDocuments"); } }
    }

}
