//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class TockePredlagatelj : XPLiteObject
    {
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        double fSifraPredlagatelja;
        public double SifraPredlagatelja
        {
            get { return fSifraPredlagatelja; }
            set { SetPropertyValue<double>("SifraPredlagatelja", ref fSifraPredlagatelja, value); }
        }
        string fUporabnik;
        [Size(255)]
        public string Uporabnik
        {
            get { return fUporabnik; }
            set { SetPropertyValue<string>("Uporabnik", ref fUporabnik, value); }
        }
        double fTockePredlagatelj1;
        [Persistent(@"TockePredlagatelj")]
        public double TockePredlagatelj1
        {
            get { return fTockePredlagatelj1; }
            set { SetPropertyValue<double>("TockePredlagatelj1", ref fTockePredlagatelj1, value); }
        }
    }

}
