//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class Users : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        bool fDeleted;
        public bool Deleted
        {
            get { return fDeleted; }
            set { SetPropertyValue<bool>("Deleted", ref fDeleted, value); }
        }
        string fLastname;
        [Size(255)]
        public string Lastname
        {
            get { return fLastname; }
            set { SetPropertyValue<string>("Lastname", ref fLastname, value); }
        }
        string fFirstname;
        [Size(255)]
        public string Firstname
        {
            get { return fFirstname; }
            set { SetPropertyValue<string>("Firstname", ref fFirstname, value); }
        }
        string fMemo;
        [Size(255)]
        public string Memo
        {
            get { return fMemo; }
            set { SetPropertyValue<string>("Memo", ref fMemo, value); }
        }
        string fPicture;
        [Size(255)]
        public string Picture
        {
            get { return fPicture; }
            set { SetPropertyValue<string>("Picture", ref fPicture, value); }
        }
        int fCompanyId;
        public int CompanyId
        {
            get { return fCompanyId; }
            set { SetPropertyValue<int>("CompanyId", ref fCompanyId, value); }
        }
        Departments fDepartmentId;
        [Association(@"UsersReferencesDepartments")]
        public Departments DepartmentId
        {
            get { return fDepartmentId; }
            set { SetPropertyValue<Departments>("DepartmentId", ref fDepartmentId, value); }
        }
        int fSubunitId;
        public int SubunitId
        {
            get { return fSubunitId; }
            set { SetPropertyValue<int>("SubunitId", ref fSubunitId, value); }
        }
        string fExternalId;
        [Size(255)]
        public string ExternalId
        {
            get { return fExternalId; }
            set { SetPropertyValue<string>("ExternalId", ref fExternalId, value); }
        }
        string fExportId;
        [Size(255)]
        public string ExportId
        {
            get { return fExportId; }
            set { SetPropertyValue<string>("ExportId", ref fExportId, value); }
        }
        string fCard;
        [Size(255)]
        public string Card
        {
            get { return fCard; }
            set { SetPropertyValue<string>("Card", ref fCard, value); }
        }
        string fCardProtected;
        [Size(255)]
        public string CardProtected
        {
            get { return fCardProtected; }
            set { SetPropertyValue<string>("CardProtected", ref fCardProtected, value); }
        }
        string fPin;
        [Size(255)]
        public string Pin
        {
            get { return fPin; }
            set { SetPropertyValue<string>("Pin", ref fPin, value); }
        }
        string fPersonalId;
        [Size(255)]
        public string PersonalId
        {
            get { return fPersonalId; }
            set { SetPropertyValue<string>("PersonalId", ref fPersonalId, value); }
        }
        string fCode;
        [Size(255)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>("Code", ref fCode, value); }
        }
        DateTime fValidTill;
        public DateTime ValidTill
        {
            get { return fValidTill; }
            set { SetPropertyValue<DateTime>("ValidTill", ref fValidTill, value); }
        }
        bool fUseKeypad;
        public bool UseKeypad
        {
            get { return fUseKeypad; }
            set { SetPropertyValue<bool>("UseKeypad", ref fUseKeypad, value); }
        }
        bool fFollow;
        public bool Follow
        {
            get { return fFollow; }
            set { SetPropertyValue<bool>("Follow", ref fFollow, value); }
        }
        bool fHide;
        public bool Hide
        {
            get { return fHide; }
            set { SetPropertyValue<bool>("Hide", ref fHide, value); }
        }
        bool fMaster;
        public bool Master
        {
            get { return fMaster; }
            set { SetPropertyValue<bool>("Master", ref fMaster, value); }
        }
        int fLinkCode;
        public int LinkCode
        {
            get { return fLinkCode; }
            set { SetPropertyValue<int>("LinkCode", ref fLinkCode, value); }
        }
        bool fBlocked;
        public bool Blocked
        {
            get { return fBlocked; }
            set { SetPropertyValue<bool>("Blocked", ref fBlocked, value); }
        }
        int fDynamicAccess;
        public int DynamicAccess
        {
            get { return fDynamicAccess; }
            set { SetPropertyValue<int>("DynamicAccess", ref fDynamicAccess, value); }
        }
        int fLastEventId;
        public int LastEventId
        {
            get { return fLastEventId; }
            set { SetPropertyValue<int>("LastEventId", ref fLastEventId, value); }
        }
        int fLastEventType;
        public int LastEventType
        {
            get { return fLastEventType; }
            set { SetPropertyValue<int>("LastEventType", ref fLastEventType, value); }
        }
        int fLastEventPlaceId;
        public int LastEventPlaceId
        {
            get { return fLastEventPlaceId; }
            set { SetPropertyValue<int>("LastEventPlaceId", ref fLastEventPlaceId, value); }
        }
        DateTime fLastEventTime;
        public DateTime LastEventTime
        {
            get { return fLastEventTime; }
            set { SetPropertyValue<DateTime>("LastEventTime", ref fLastEventTime, value); }
        }
        bool fIsTimeAttendance;
        public bool IsTimeAttendance
        {
            get { return fIsTimeAttendance; }
            set { SetPropertyValue<bool>("IsTimeAttendance", ref fIsTimeAttendance, value); }
        }
        bool fIsLoginAllowed;
        public bool IsLoginAllowed
        {
            get { return fIsLoginAllowed; }
            set { SetPropertyValue<bool>("IsLoginAllowed", ref fIsLoginAllowed, value); }
        }
        string fUsername;
        [Size(255)]
        public string Username
        {
            get { return fUsername; }
            set { SetPropertyValue<string>("Username", ref fUsername, value); }
        }
        string fPassword;
        [Size(255)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>("Password", ref fPassword, value); }
        }
        string fLanguage;
        [Size(255)]
        public string Language
        {
            get { return fLanguage; }
            set { SetPropertyValue<string>("Language", ref fLanguage, value); }
        }
        string fEmail;
        [Size(255)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        int fCardType;
        public int CardType
        {
            get { return fCardType; }
            set { SetPropertyValue<int>("CardType", ref fCardType, value); }
        }
        DateTime fTAStartDate;
        public DateTime TAStartDate
        {
            get { return fTAStartDate; }
            set { SetPropertyValue<DateTime>("TAStartDate", ref fTAStartDate, value); }
        }
        int fCalendarId;
        public int CalendarId
        {
            get { return fCalendarId; }
            set { SetPropertyValue<int>("CalendarId", ref fCalendarId, value); }
        }
        DateTime fValidFrom;
        public DateTime ValidFrom
        {
            get { return fValidFrom; }
            set { SetPropertyValue<DateTime>("ValidFrom", ref fValidFrom, value); }
        }
        bool fLostCard;
        public bool LostCard
        {
            get { return fLostCard; }
            set { SetPropertyValue<bool>("LostCard", ref fLostCard, value); }
        }
        bool fMobileCard;
        public bool MobileCard
        {
            get { return fMobileCard; }
            set { SetPropertyValue<bool>("MobileCard", ref fMobileCard, value); }
        }
        bool fEditOwnTA;
        public bool EditOwnTA
        {
            get { return fEditOwnTA; }
            set { SetPropertyValue<bool>("EditOwnTA", ref fEditOwnTA, value); }
        }
        bool fEditOwnYearData;
        public bool EditOwnYearData
        {
            get { return fEditOwnYearData; }
            set { SetPropertyValue<bool>("EditOwnYearData", ref fEditOwnYearData, value); }
        }
        bool fProcessOwnAbsences;
        public bool ProcessOwnAbsences
        {
            get { return fProcessOwnAbsences; }
            set { SetPropertyValue<bool>("ProcessOwnAbsences", ref fProcessOwnAbsences, value); }
        }
        bool fProcessOwnPermits;
        public bool ProcessOwnPermits
        {
            get { return fProcessOwnPermits; }
            set { SetPropertyValue<bool>("ProcessOwnPermits", ref fProcessOwnPermits, value); }
        }
        string fCustomField1;
        [Size(255)]
        public string CustomField1
        {
            get { return fCustomField1; }
            set { SetPropertyValue<string>("CustomField1", ref fCustomField1, value); }
        }
        string fCustomField2;
        [Size(255)]
        public string CustomField2
        {
            get { return fCustomField2; }
            set { SetPropertyValue<string>("CustomField2", ref fCustomField2, value); }
        }
        string fCustomField3;
        [Size(255)]
        public string CustomField3
        {
            get { return fCustomField3; }
            set { SetPropertyValue<string>("CustomField3", ref fCustomField3, value); }
        }
        bool fViewOwnTimeAndAttendance;
        public bool ViewOwnTimeAndAttendance
        {
            get { return fViewOwnTimeAndAttendance; }
            set { SetPropertyValue<bool>("ViewOwnTimeAndAttendance", ref fViewOwnTimeAndAttendance, value); }
        }
        bool fAllowPlaceReservations;
        public bool AllowPlaceReservations
        {
            get { return fAllowPlaceReservations; }
            set { SetPropertyValue<bool>("AllowPlaceReservations", ref fAllowPlaceReservations, value); }
        }
        bool fAllowGuests;
        public bool AllowGuests
        {
            get { return fAllowGuests; }
            set { SetPropertyValue<bool>("AllowGuests", ref fAllowGuests, value); }
        }
        bool fIsAlternativeActionActive;
        public bool IsAlternativeActionActive
        {
            get { return fIsAlternativeActionActive; }
            set { SetPropertyValue<bool>("IsAlternativeActionActive", ref fIsAlternativeActionActive, value); }
        }
        Vloga fRoleID;
        [Association(@"UsersReferencesVloga")]
        public Vloga RoleID
        {
            get { return fRoleID; }
            set { SetPropertyValue<Vloga>("RoleID", ref fRoleID, value); }
        }
        int fTockeSK;
        public int TockeSK
        {
            get { return fTockeSK; }
            set { SetPropertyValue<int>("TockeSK", ref fTockeSK, value); }
        }
        int fTockeKVP;
        public int TockeKVP
        {
            get { return fTockeKVP; }
            set { SetPropertyValue<int>("TockeKVP", ref fTockeKVP, value); }
        }
        int fTockeKVPRealizator;
        public int TockeKVPRealizator
        {
            get { return fTockeKVPRealizator; }
            set { SetPropertyValue<int>("TockeKVPRealizator", ref fTockeKVPRealizator, value); }
        }
        int fStMojiKVP;
        public int StMojiKVP
        {
            get { return fStMojiKVP; }
            set { SetPropertyValue<int>("StMojiKVP", ref fStMojiKVP, value); }
        }
        int fStPotrjeniKVP;
        public int StPotrjeniKVP
        {
            get { return fStPotrjeniKVP; }
            set { SetPropertyValue<int>("StPotrjeniKVP", ref fStPotrjeniKVP, value); }
        }
        int fStZavrnjeniKVP;
        public int StZavrnjeniKVP
        {
            get { return fStZavrnjeniKVP; }
            set { SetPropertyValue<int>("StZavrnjeniKVP", ref fStZavrnjeniKVP, value); }
        }
        int fStOstaloKVP;
        public int StOstaloKVP
        {
            get { return fStOstaloKVP; }
            set { SetPropertyValue<int>("StOstaloKVP", ref fStOstaloKVP, value); }
        }
        int fTockeTekociMesec;
        public int TockeTekociMesec
        {
            get { return fTockeTekociMesec; }
            set { SetPropertyValue<int>("TockeTekociMesec", ref fTockeTekociMesec, value); }
        }
        int fTockeRealizatorTekociMesec;
        public int TockeRealizatorTekociMesec
        {
            get { return fTockeRealizatorTekociMesec; }
            set { SetPropertyValue<int>("TockeRealizatorTekociMesec", ref fTockeRealizatorTekociMesec, value); }
        }
        bool fUpravicenDoKVP;
        public bool UpravicenDoKVP
        {
            get { return fUpravicenDoKVP; }
            set { SetPropertyValue<bool>("UpravicenDoKVP", ref fUpravicenDoKVP, value); }
        }
        int fUserReferenceId;
        public int UserReferenceId
        {
            get { return fUserReferenceId; }
            set { SetPropertyValue<int>("UserReferenceId", ref fUserReferenceId, value); }
        }
        bool fPaysForLunch;
        public bool PaysForLunch
        {
            get { return fPaysForLunch; }
            set { SetPropertyValue<bool>("PaysForLunch", ref fPaysForLunch, value); }
        }
        bool fChangedDepartment;
        public bool ChangedDepartment
        {
            get { return fChangedDepartment; }
            set { SetPropertyValue<bool>("ChangedDepartment", ref fChangedDepartment, value); }
        }
        bool fUpravicenDoEPoste;
        public bool UpravicenDoEPoste
        {
            get { return fUpravicenDoEPoste; }
            set { SetPropertyValue<bool>("UpravicenDoEPoste", ref fUpravicenDoEPoste, value); }
        }
        bool feKVPPrijava;
        public bool eKVPPrijava
        {
            get { return feKVPPrijava; }
            set { SetPropertyValue<bool>("eKVPPrijava", ref feKVPPrijava, value); }
        }
        int fNotEmployedAnymore;
        public int NotEmployedAnymore
        {
            get { return fNotEmployedAnymore; }
            set { SetPropertyValue<int>("NotEmployedAnymore", ref fNotEmployedAnymore, value); }
        }
        int fNewEmployee;
        public int NewEmployee
        {
            get { return fNewEmployee; }
            set { SetPropertyValue<int>("NewEmployee", ref fNewEmployee, value); }
        }
        int fIsDuplicated;
        public int IsDuplicated
        {
            get { return fIsDuplicated; }
            set { SetPropertyValue<int>("IsDuplicated", ref fIsDuplicated, value); }
        }
        int fNameChanged;
        public int NameChanged
        {
            get { return fNameChanged; }
            set { SetPropertyValue<int>("NameChanged", ref fNameChanged, value); }
        }
        bool fPozarniReferent;
        public bool PozarniReferent
        {
            get { return fPozarniReferent; }
            set { SetPropertyValue<bool>("PozarniReferent", ref fPozarniReferent, value); }
        }
        Vloga fSecondRoleID;
        [Association(@"UsersReferencesVloga1")]
        public Vloga SecondRoleID
        {
            get { return fSecondRoleID; }
            set { SetPropertyValue<Vloga>("SecondRoleID", ref fSecondRoleID, value); }
        }
        int fSinhronizationNo;
        public int SinhronizationNo
        {
            get { return fSinhronizationNo; }
            set { SetPropertyValue<int>("SinhronizationNo", ref fSinhronizationNo, value); }
        }
        DateTime fLastSinhroDate;
        public DateTime LastSinhroDate
        {
            get { return fLastSinhroDate; }
            set { SetPropertyValue<DateTime>("LastSinhroDate", ref fLastSinhroDate, value); }
        }
        bool fEmployeeLeaveCompany;
        public bool EmployeeLeaveCompany
        {
            get { return fEmployeeLeaveCompany; }
            set { SetPropertyValue<bool>("EmployeeLeaveCompany", ref fEmployeeLeaveCompany, value); }
        }
        [Association(@"IzplacilaReferencesUsers")]
        public XPCollection<Izplacila> Izplacilas { get { return GetCollection<Izplacila>("Izplacilas"); } }
        [Association(@"KVPSkupina_UsersReferencesUsers")]
        public XPCollection<KVPSkupina_Users> KVPSkupina_Userss { get { return GetCollection<KVPSkupina_Users>("KVPSkupina_Userss"); } }
        [Association(@"OddelekReferencesUsers")]
        public XPCollection<Oddelek> Oddeleks { get { return GetCollection<Oddelek>("Oddeleks"); } }
        [Association(@"OddelekReferencesUsers1")]
        public XPCollection<Oddelek> Oddeleks1 { get { return GetCollection<Oddelek>("Oddeleks1"); } }
        [Association(@"KVPPresojeReferencesUsers")]
        public XPCollection<KVPPresoje> KVPPresojes { get { return GetCollection<KVPPresoje>("KVPPresojes"); } }
        [Association(@"KVPSkupinaReferencesUsers")]
        public XPCollection<KVPSkupina> KVPSkupinas { get { return GetCollection<KVPSkupina>("KVPSkupinas"); } }
        [Association(@"KVPSkupinaReferencesUsers1")]
        public XPCollection<KVPSkupina> KVPSkupinas1 { get { return GetCollection<KVPSkupina>("KVPSkupinas1"); } }
        [Association(@"KVPSkupinaReferencesUsers2")]
        public XPCollection<KVPSkupina> KVPSkupinas2 { get { return GetCollection<KVPSkupina>("KVPSkupinas2"); } }
        [Association(@"KVPKomentarjiReferencesUsers")]
        public XPCollection<KVPKomentarji> KVPKomentarjis { get { return GetCollection<KVPKomentarji>("KVPKomentarjis"); } }
        [Association(@"PrispevekReferencesUsers")]
        public XPCollection<Prispevek> Prispeveks { get { return GetCollection<Prispevek>("Prispeveks"); } }
        [Association(@"KVP_StatusReferencesUsers")]
        public XPCollection<KVP_Status> KVP_Statuss { get { return GetCollection<KVP_Status>("KVP_Statuss"); } }
        [Association(@"ActiveUserReferencesUsers")]
        public XPCollection<ActiveUser> ActiveUsers { get { return GetCollection<ActiveUser>("ActiveUsers"); } }
        [Association(@"KVPDocumentReferencesUsers")]
        public XPCollection<KVPDocument> KVPDocuments { get { return GetCollection<KVPDocument>("KVPDocuments"); } }
        [Association(@"KVPDocumentReferencesUsers1")]
        public XPCollection<KVPDocument> KVPDocuments1 { get { return GetCollection<KVPDocument>("KVPDocuments1"); } }
        [Association(@"KVPDocumentReferencesUsers2")]
        public XPCollection<KVPDocument> KVPDocuments2 { get { return GetCollection<KVPDocument>("KVPDocuments2"); } }
        [Association(@"KVPDocumentReferencesUsers3")]
        public XPCollection<KVPDocument> KVPDocuments3 { get { return GetCollection<KVPDocument>("KVPDocuments3"); } }
        [Association(@"KVPDocumentReferencesUsers4")]
        public XPCollection<KVPDocument> KVPDocuments4 { get { return GetCollection<KVPDocument>("KVPDocuments4"); } }
        [Association(@"KVPDocumentReferencesUsers5")]
        public XPCollection<KVPDocument> KVPDocuments5 { get { return GetCollection<KVPDocument>("KVPDocuments5"); } }
    }

}
