//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class Zaposleni : XPLiteObject
    {
        int fidZaposleni;
        [Key(true)]
        public int idZaposleni
        {
            get { return fidZaposleni; }
            set { SetPropertyValue<int>("idZaposleni", ref fidZaposleni, value); }
        }
        decimal fJantarKoda;
        public decimal JantarKoda
        {
            get { return fJantarKoda; }
            set { SetPropertyValue<decimal>("JantarKoda", ref fJantarKoda, value); }
        }
        string fVloga;
        [Size(50)]
        public string Vloga
        {
            get { return fVloga; }
            set { SetPropertyValue<string>("Vloga", ref fVloga, value); }
        }
        string fIme;
        [Size(50)]
        public string Ime
        {
            get { return fIme; }
            set { SetPropertyValue<string>("Ime", ref fIme, value); }
        }
        string fPriimek;
        [Size(200)]
        public string Priimek
        {
            get { return fPriimek; }
            set { SetPropertyValue<string>("Priimek", ref fPriimek, value); }
        }
        string fNaziv;
        [Size(200)]
        public string Naziv
        {
            get { return fNaziv; }
            set { SetPropertyValue<string>("Naziv", ref fNaziv, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
        string fUporabniskoIme;
        [Size(50)]
        public string UporabniskoIme
        {
            get { return fUporabniskoIme; }
            set { SetPropertyValue<string>("UporabniskoIme", ref fUporabniskoIme, value); }
        }
        string fGeslo;
        [Size(30)]
        public string Geslo
        {
            get { return fGeslo; }
            set { SetPropertyValue<string>("Geslo", ref fGeslo, value); }
        }
        [Association(@"HierarhijaReferencesZaposleni")]
        public XPCollection<Hierarhija> Hierarhijas { get { return GetCollection<Hierarhija>("Hierarhijas"); } }
        [Association(@"HierarhijaReferencesZaposleni1")]
        public XPCollection<Hierarhija> Hierarhijas1 { get { return GetCollection<Hierarhija>("Hierarhijas1"); } }
    }

}
