//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVP_Obrazci.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthenticationValidation_Exception {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationValidation_Exception() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KVP_Obrazci.Resources.AuthenticationValidation_Exception", typeof(AuthenticationValidation_Exception).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napačna prijava! Ponovno vnesi geslo in uporabniško ime!.
        /// </summary>
        public static string res_01 {
            get {
                return ResourceManager.GetString("res_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napačna prijava! Uporabnik nima dodeljene vloge! Obrnite se na adminstratorja!.
        /// </summary>
        public static string res_02 {
            get {
                return ResourceManager.GetString("res_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napačna prijava! Uporabnik nima dodeljene KVP skupine! Obrnite se na administratorja!.
        /// </summary>
        public static string res_03 {
            get {
                return ResourceManager.GetString("res_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napačna prijava! Uporabnik nima odobrenega dostopa do eKVP sistema!.
        /// </summary>
        public static string res_04 {
            get {
                return ResourceManager.GetString("res_04", resourceCulture);
            }
        }
    }
}
