//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class ActiveUser : XPLiteObject
    {
        int fActiveUserID;
        [Key(true)]
        public int ActiveUserID
        {
            get { return fActiveUserID; }
            set { SetPropertyValue<int>("ActiveUserID", ref fActiveUserID, value); }
        }
        Users fUserID;
        [Association(@"ActiveUserReferencesUsers")]
        public Users UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<Users>("UserID", ref fUserID, value); }
        }
        DateTime fLogInDate;
        public DateTime LogInDate
        {
            get { return fLogInDate; }
            set { SetPropertyValue<DateTime>("LogInDate", ref fLogInDate, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>("IsActive", ref fIsActive, value); }
        }
        DateTime fLastRequestTS;
        public DateTime LastRequestTS
        {
            get { return fLastRequestTS; }
            set { SetPropertyValue<DateTime>("LastRequestTS", ref fLastRequestTS, value); }
        }
        int fRequestCount;
        public int RequestCount
        {
            get { return fRequestCount; }
            set { SetPropertyValue<int>("RequestCount", ref fRequestCount, value); }
        }
        string fNotes;
        [Size(1000)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>("Notes", ref fNotes, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
    }

}
