//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class KVPExcellDokumenti : XPLiteObject
    {
        double fLetoIdeje;
        public double LetoIdeje
        {
            get { return fLetoIdeje; }
            set { SetPropertyValue<double>("LetoIdeje", ref fLetoIdeje, value); }
        }
        double fMesecIdeje;
        public double MesecIdeje
        {
            get { return fMesecIdeje; }
            set { SetPropertyValue<double>("MesecIdeje", ref fMesecIdeje, value); }
        }
        int fZapSt;
        public int ZapSt
        {
            get { return fZapSt; }
            set { SetPropertyValue<int>("ZapSt", ref fZapSt, value); }
        }
        string fStKVP;
        [Size(255)]
        [Persistent(@" StKVP ")]
        public string StKVP
        {
            get { return fStKVP; }
            set { SetPropertyValue<string>("StKVP", ref fStKVP, value); }
        }
        string fKVPSkupina;
        [Size(255)]
        public string KVPSkupina
        {
            get { return fKVPSkupina; }
            set { SetPropertyValue<string>("KVPSkupina", ref fKVPSkupina, value); }
        }
        DateTime fDatumVnosa;
        public DateTime DatumVnosa
        {
            get { return fDatumVnosa; }
            set { SetPropertyValue<DateTime>("DatumVnosa", ref fDatumVnosa, value); }
        }
        string fUporabnik;
        [Size(255)]
        public string Uporabnik
        {
            get { return fUporabnik; }
            set { SetPropertyValue<string>("Uporabnik", ref fUporabnik, value); }
        }
        string fOpisKVPIdeje;
        [Size(4000)]
        public string OpisKVPIdeje
        {
            get { return fOpisKVPIdeje; }
            set { SetPropertyValue<string>("OpisKVPIdeje", ref fOpisKVPIdeje, value); }
        }
        string fVodjaZaOdIdeje;
        [Size(255)]
        public string VodjaZaOdIdeje
        {
            get { return fVodjaZaOdIdeje; }
            set { SetPropertyValue<string>("VodjaZaOdIdeje", ref fVodjaZaOdIdeje, value); }
        }
        string fPresoja;
        [Size(255)]
        public string Presoja
        {
            get { return fPresoja; }
            set { SetPropertyValue<string>("Presoja", ref fPresoja, value); }
        }
        string fRealizator;
        [Size(255)]
        public string Realizator
        {
            get { return fRealizator; }
            set { SetPropertyValue<string>("Realizator", ref fRealizator, value); }
        }
        DateTime fDatumZakljIdeje;
        public DateTime DatumZakljIdeje
        {
            get { return fDatumZakljIdeje; }
            set { SetPropertyValue<DateTime>("DatumZakljIdeje", ref fDatumZakljIdeje, value); }
        }
        double fSprejel;
        public double Sprejel
        {
            get { return fSprejel; }
            set { SetPropertyValue<double>("Sprejel", ref fSprejel, value); }
        }
        double fZavrnil;
        public double Zavrnil
        {
            get { return fZavrnil; }
            set { SetPropertyValue<double>("Zavrnil", ref fZavrnil, value); }
        }
        string fRealiziral;
        [Size(255)]
        public string Realiziral
        {
            get { return fRealiziral; }
            set { SetPropertyValue<string>("Realiziral", ref fRealiziral, value); }
        }
        string fopombe;
        [Size(255)]
        public string opombe
        {
            get { return fopombe; }
            set { SetPropertyValue<string>("opombe", ref fopombe, value); }
        }
        double fCASDOGOTOVEIDEJE;
        public double CASDOGOTOVEIDEJE
        {
            get { return fCASDOGOTOVEIDEJE; }
            set { SetPropertyValue<double>("CASDOGOTOVEIDEJE", ref fCASDOGOTOVEIDEJE, value); }
        }
        string fSkupina;
        [Size(255)]
        public string Skupina
        {
            get { return fSkupina; }
            set { SetPropertyValue<string>("Skupina", ref fSkupina, value); }
        }
        string fTipIdeje;
        [Size(255)]
        public string TipIdeje
        {
            get { return fTipIdeje; }
            set { SetPropertyValue<string>("TipIdeje", ref fTipIdeje, value); }
        }
        string fTPredlagatelj;
        [Size(255)]
        public string TPredlagatelj
        {
            get { return fTPredlagatelj; }
            set { SetPropertyValue<string>("TPredlagatelj", ref fTPredlagatelj, value); }
        }
        string fTRealizator;
        [Size(255)]
        public string TRealizator
        {
            get { return fTRealizator; }
            set { SetPropertyValue<string>("TRealizator", ref fTRealizator, value); }
        }
        double fIDZaposlenega;
        public double IDZaposlenega
        {
            get { return fIDZaposlenega; }
            set { SetPropertyValue<double>("IDZaposlenega", ref fIDZaposlenega, value); }
        }
        double fCIPPrihranek;
        public double CIPPrihranek
        {
            get { return fCIPPrihranek; }
            set { SetPropertyValue<double>("CIPPrihranek", ref fCIPPrihranek, value); }
        }
        double fLeto2;
        public double Leto2
        {
            get { return fLeto2; }
            set { SetPropertyValue<double>("Leto2", ref fLeto2, value); }
        }
        double fMesec2;
        public double Mesec2
        {
            get { return fMesec2; }
            set { SetPropertyValue<double>("Mesec2", ref fMesec2, value); }
        }
        string fIzplaciloTock;
        [Size(255)]
        public string IzplaciloTock
        {
            get { return fIzplaciloTock; }
            set { SetPropertyValue<string>("IzplaciloTock", ref fIzplaciloTock, value); }
        }
        double fSifPredlagatelja;
        public double SifPredlagatelja
        {
            get { return fSifPredlagatelja; }
            set { SetPropertyValue<double>("SifPredlagatelja", ref fSifPredlagatelja, value); }
        }
        double fSifRealizator;
        public double SifRealizator
        {
            get { return fSifRealizator; }
            set { SetPropertyValue<double>("SifRealizator", ref fSifRealizator, value); }
        }
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        int fInsertedDB;
        public int InsertedDB
        {
            get { return fInsertedDB; }
            set { SetPropertyValue<int>("InsertedDB", ref fInsertedDB, value); }
        }
    }

}
