//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class KVPSkupina_Users : XPLiteObject
    {
        int fidKVPSkupina_Zaposleni;
        [Key(true)]
        public int idKVPSkupina_Zaposleni
        {
            get { return fidKVPSkupina_Zaposleni; }
            set { SetPropertyValue<int>("idKVPSkupina_Zaposleni", ref fidKVPSkupina_Zaposleni, value); }
        }
        KVPSkupina fidKVPSkupina;
        [Association(@"KVPSkupina_UsersReferencesKVPSkupina")]
        public KVPSkupina idKVPSkupina
        {
            get { return fidKVPSkupina; }
            set { SetPropertyValue<KVPSkupina>("idKVPSkupina", ref fidKVPSkupina, value); }
        }
        Users fIdUser;
        [Association(@"KVPSkupina_UsersReferencesUsers")]
        public Users IdUser
        {
            get { return fIdUser; }
            set { SetPropertyValue<Users>("IdUser", ref fIdUser, value); }
        }
        bool fChampion;
        public bool Champion
        {
            get { return fChampion; }
            set { SetPropertyValue<bool>("Champion", ref fChampion, value); }
        }
        int fIDPrijave;
        public int IDPrijave
        {
            get { return fIDPrijave; }
            set { SetPropertyValue<int>("IDPrijave", ref fIDPrijave, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
    }

}
