//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class Oddelek : XPLiteObject
    {
        int fidOddelek;
        [Key(true)]
        public int idOddelek
        {
            get { return fidOddelek; }
            set { SetPropertyValue<int>("idOddelek", ref fidOddelek, value); }
        }
        Users fVodja;
        [Association(@"OddelekReferencesUsers1")]
        public Users Vodja
        {
            get { return fVodja; }
            set { SetPropertyValue<Users>("Vodja", ref fVodja, value); }
        }
        Users fNadomestniVodja;
        [Association(@"OddelekReferencesUsers")]
        public Users NadomestniVodja
        {
            get { return fNadomestniVodja; }
            set { SetPropertyValue<Users>("NadomestniVodja", ref fNadomestniVodja, value); }
        }
        string fKoda;
        [Size(20)]
        public string Koda
        {
            get { return fKoda; }
            set { SetPropertyValue<string>("Koda", ref fKoda, value); }
        }
        string fNaziv;
        [Size(200)]
        public string Naziv
        {
            get { return fNaziv; }
            set { SetPropertyValue<string>("Naziv", ref fNaziv, value); }
        }
    }

}
