//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class SystemMessageProcessor : XPLiteObject
    {
        int fSystemMessageEventID;
        [Key(true)]
        public int SystemMessageEventID
        {
            get { return fSystemMessageEventID; }
            set { SetPropertyValue<int>("SystemMessageEventID", ref fSystemMessageEventID, value); }
        }
        int fMasterID;
        public int MasterID
        {
            get { return fMasterID; }
            set { SetPropertyValue<int>("MasterID", ref fMasterID, value); }
        }
        string fCode;
        [Size(50)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>("Code", ref fCode, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>("Status", ref fStatus, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
        int ftsIDOsebe;
        public int tsIDOsebe
        {
            get { return ftsIDOsebe; }
            set { SetPropertyValue<int>("tsIDOsebe", ref ftsIDOsebe, value); }
        }
    }

}
