//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class TockeRealizator : XPLiteObject
    {
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        double fSifraRealizator;
        public double SifraRealizator
        {
            get { return fSifraRealizator; }
            set { SetPropertyValue<double>("SifraRealizator", ref fSifraRealizator, value); }
        }
        string fRealizator;
        [Size(255)]
        public string Realizator
        {
            get { return fRealizator; }
            set { SetPropertyValue<string>("Realizator", ref fRealizator, value); }
        }
        double fTockeRealizator1;
        [Persistent(@"TockeRealizator")]
        public double TockeRealizator1
        {
            get { return fTockeRealizator1; }
            set { SetPropertyValue<double>("TockeRealizator1", ref fTockeRealizator1, value); }
        }
    }

}
