//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class TockeDec2018 : XPLiteObject
    {
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fUporabnik;
        [Size(255)]
        public string Uporabnik
        {
            get { return fUporabnik; }
            set { SetPropertyValue<string>("Uporabnik", ref fUporabnik, value); }
        }
        string fOddelek;
        [Size(255)]
        public string Oddelek
        {
            get { return fOddelek; }
            set { SetPropertyValue<string>("Oddelek", ref fOddelek, value); }
        }
        string fKVPSKUPINA;
        [Size(255)]
        [Persistent(@"KVP SKUPINA")]
        public string KVPSKUPINA
        {
            get { return fKVPSKUPINA; }
            set { SetPropertyValue<string>("KVPSKUPINA", ref fKVPSKUPINA, value); }
        }
        double fKoda;
        public double Koda
        {
            get { return fKoda; }
            set { SetPropertyValue<double>("Koda", ref fKoda, value); }
        }
        double fPrenos;
        public double Prenos
        {
            get { return fPrenos; }
            set { SetPropertyValue<double>("Prenos", ref fPrenos, value); }
        }
    }

}
