//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.KVPOdelo
{

    public partial class zaposleni_tocke : XPLiteObject
    {
        int fId;
        [Key]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        double fKoda;
        public double Koda
        {
            get { return fKoda; }
            set { SetPropertyValue<double>("Koda", ref fKoda, value); }
        }
        string fUporabnik;
        [Size(255)]
        public string Uporabnik
        {
            get { return fUporabnik; }
            set { SetPropertyValue<string>("Uporabnik", ref fUporabnik, value); }
        }
        string fOddelek;
        [Size(255)]
        public string Oddelek
        {
            get { return fOddelek; }
            set { SetPropertyValue<string>("Oddelek", ref fOddelek, value); }
        }
        string fKVPSKUPINA;
        [Size(255)]
        [Persistent(@"KVP SKUPINA")]
        public string KVPSKUPINA
        {
            get { return fKVPSKUPINA; }
            set { SetPropertyValue<string>("KVPSKUPINA", ref fKVPSKUPINA, value); }
        }
        double fKoda1;
        public double Koda1
        {
            get { return fKoda1; }
            set { SetPropertyValue<double>("Koda1", ref fKoda1, value); }
        }
        double fPrenos;
        [Persistent(@"Prenos ")]
        public double Prenos
        {
            get { return fPrenos; }
            set { SetPropertyValue<double>("Prenos", ref fPrenos, value); }
        }
        double fPredlagatelj;
        public double Predlagatelj
        {
            get { return fPredlagatelj; }
            set { SetPropertyValue<double>("Predlagatelj", ref fPredlagatelj, value); }
        }
        double fRealizator;
        public double Realizator
        {
            get { return fRealizator; }
            set { SetPropertyValue<double>("Realizator", ref fRealizator, value); }
        }
        double fSum;
        public double Sum
        {
            get { return fSum; }
            set { SetPropertyValue<double>("Sum", ref fSum, value); }
        }
        decimal fIzplačilotočkv_;
        [Persistent(@"Izplačilo točk v €")]
        public decimal Izplačilotočkv_
        {
            get { return fIzplačilotočkv_; }
            set { SetPropertyValue<decimal>("Izplačilotočkv_", ref fIzplačilotočkv_, value); }
        }
        double fPrenos1;
        [Persistent(@"Prenos 1")]
        public double Prenos1
        {
            get { return fPrenos1; }
            set { SetPropertyValue<double>("Prenos1", ref fPrenos1, value); }
        }
        double fPredlagatelj1;
        public double Predlagatelj1
        {
            get { return fPredlagatelj1; }
            set { SetPropertyValue<double>("Predlagatelj1", ref fPredlagatelj1, value); }
        }
        double fRealizator1;
        public double Realizator1
        {
            get { return fRealizator1; }
            set { SetPropertyValue<double>("Realizator1", ref fRealizator1, value); }
        }
        double fSum1;
        public double Sum1
        {
            get { return fSum1; }
            set { SetPropertyValue<double>("Sum1", ref fSum1, value); }
        }
        decimal fIzplačilotočkv_1;
        [Persistent(@"Izplačilo točk v €1")]
        public decimal Izplačilotočkv_1
        {
            get { return fIzplačilotočkv_1; }
            set { SetPropertyValue<decimal>("Izplačilotočkv_1", ref fIzplačilotočkv_1, value); }
        }
        double fPrenos2;
        [Persistent(@"Prenos 2")]
        public double Prenos2
        {
            get { return fPrenos2; }
            set { SetPropertyValue<double>("Prenos2", ref fPrenos2, value); }
        }
        double fPredlagatelj2;
        public double Predlagatelj2
        {
            get { return fPredlagatelj2; }
            set { SetPropertyValue<double>("Predlagatelj2", ref fPredlagatelj2, value); }
        }
        double fRealizator2;
        public double Realizator2
        {
            get { return fRealizator2; }
            set { SetPropertyValue<double>("Realizator2", ref fRealizator2, value); }
        }
        double fSum2;
        public double Sum2
        {
            get { return fSum2; }
            set { SetPropertyValue<double>("Sum2", ref fSum2, value); }
        }
        decimal fIzplačilotočkv_2;
        [Persistent(@"Izplačilo točk v €2")]
        public decimal Izplačilotočkv_2
        {
            get { return fIzplačilotočkv_2; }
            set { SetPropertyValue<decimal>("Izplačilotočkv_2", ref fIzplačilotočkv_2, value); }
        }
        double fPrenosnaslednjimesec;
        [Persistent(@"Prenos naslednji mesec")]
        public double Prenosnaslednjimesec
        {
            get { return fPrenosnaslednjimesec; }
            set { SetPropertyValue<double>("Prenosnaslednjimesec", ref fPrenosnaslednjimesec, value); }
        }
    }

}
