//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVP_Obrazci.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DB_Exception {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DB_Exception() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KVP_Obrazci.Resources.DB_Exception", typeof(DB_Exception).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRepositoryError - GET method .
        /// </summary>
        public static string res_01 {
            get {
                return ResourceManager.GetString("res_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRepositoryError - SAVE method .
        /// </summary>
        public static string res_02 {
            get {
                return ResourceManager.GetString("res_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRepositoryError - DELETE method .
        /// </summary>
        public static string res_03 {
            get {
                return ResourceManager.GetString("res_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusRepositoryError - GET method .
        /// </summary>
        public static string res_04 {
            get {
                return ResourceManager.GetString("res_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusRepositoryError - SAVE method .
        /// </summary>
        public static string res_05 {
            get {
                return ResourceManager.GetString("res_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusRepositoryError - DELETE method .
        /// </summary>
        public static string res_06 {
            get {
                return ResourceManager.GetString("res_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPStatusRepositoryError - GET method .
        /// </summary>
        public static string res_07 {
            get {
                return ResourceManager.GetString("res_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPStatusRepositoryError - SAVE method .
        /// </summary>
        public static string res_08 {
            get {
                return ResourceManager.GetString("res_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPStatusRepositoryError - DELETE method .
        /// </summary>
        public static string res_09 {
            get {
                return ResourceManager.GetString("res_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPGroupRepository - GET method.
        /// </summary>
        public static string res_10 {
            get {
                return ResourceManager.GetString("res_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPGroupRepository - SAVE method.
        /// </summary>
        public static string res_11 {
            get {
                return ResourceManager.GetString("res_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPGroupRepository - DELETE method.
        /// </summary>
        public static string res_12 {
            get {
                return ResourceManager.GetString("res_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeRepository - GET method.
        /// </summary>
        public static string res_13 {
            get {
                return ResourceManager.GetString("res_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeRepository - SAVE method.
        /// </summary>
        public static string res_14 {
            get {
                return ResourceManager.GetString("res_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeRepository - DELETE method.
        /// </summary>
        public static string res_15 {
            get {
                return ResourceManager.GetString("res_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleRepository - GET method.
        /// </summary>
        public static string res_16 {
            get {
                return ResourceManager.GetString("res_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleRepository - SAVE method.
        /// </summary>
        public static string res_17 {
            get {
                return ResourceManager.GetString("res_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleRepository - DELETE method.
        /// </summary>
        public static string res_18 {
            get {
                return ResourceManager.GetString("res_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPAuditroRepository - GET method.
        /// </summary>
        public static string res_19 {
            get {
                return ResourceManager.GetString("res_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPAuditroRepository - SAVE method.
        /// </summary>
        public static string res_20 {
            get {
                return ResourceManager.GetString("res_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPAuditroRepository - DELETE method.
        /// </summary>
        public static string res_21 {
            get {
                return ResourceManager.GetString("res_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayoutsRepository - GET method.
        /// </summary>
        public static string res_22 {
            get {
                return ResourceManager.GetString("res_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayoutsRepository - SAVE method.
        /// </summary>
        public static string res_23 {
            get {
                return ResourceManager.GetString("res_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayoutsRepository - DELETE method.
        /// </summary>
        public static string res_24 {
            get {
                return ResourceManager.GetString("res_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanRealizationRepository - GET method.
        /// </summary>
        public static string res_25 {
            get {
                return ResourceManager.GetString("res_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanRealizationRepository - SAVE method.
        /// </summary>
        public static string res_26 {
            get {
                return ResourceManager.GetString("res_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanRealizationRepository - DELETE method.
        /// </summary>
        public static string res_27 {
            get {
                return ResourceManager.GetString("res_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageProcessorRepository - GET method.
        /// </summary>
        public static string res_28 {
            get {
                return ResourceManager.GetString("res_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageProcessorRepository - SAVE method.
        /// </summary>
        public static string res_29 {
            get {
                return ResourceManager.GetString("res_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageProcessorRepository - DELETE method.
        /// </summary>
        public static string res_30 {
            get {
                return ResourceManager.GetString("res_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageSenderRepository - GET method.
        /// </summary>
        public static string res_31 {
            get {
                return ResourceManager.GetString("res_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageSenderRepository - SAVE method.
        /// </summary>
        public static string res_32 {
            get {
                return ResourceManager.GetString("res_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageSenderRepository - DELETE method.
        /// </summary>
        public static string res_33 {
            get {
                return ResourceManager.GetString("res_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanySettingsRepository - GET method.
        /// </summary>
        public static string res_34 {
            get {
                return ResourceManager.GetString("res_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanySettingsRepository - SAVE method.
        /// </summary>
        public static string res_35 {
            get {
                return ResourceManager.GetString("res_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanySettingsRepository - DELETE method.
        /// </summary>
        public static string res_36 {
            get {
                return ResourceManager.GetString("res_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPTypeRepository - GET method.
        /// </summary>
        public static string res_37 {
            get {
                return ResourceManager.GetString("res_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPTypeRepository - SAVE method.
        /// </summary>
        public static string res_38 {
            get {
                return ResourceManager.GetString("res_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVPTypeRepository - DELETE method.
        /// </summary>
        public static string res_39 {
            get {
                return ResourceManager.GetString("res_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostRepository - GET method.
        /// </summary>
        public static string res_40 {
            get {
                return ResourceManager.GetString("res_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostRepository - SAVE method.
        /// </summary>
        public static string res_41 {
            get {
                return ResourceManager.GetString("res_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostRepository - DELETE method.
        /// </summary>
        public static string res_42 {
            get {
                return ResourceManager.GetString("res_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentRepository - GET method.
        /// </summary>
        public static string res_43 {
            get {
                return ResourceManager.GetString("res_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentRepository - SAVE method.
        /// </summary>
        public static string res_44 {
            get {
                return ResourceManager.GetString("res_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentRepository - DELETE method.
        /// </summary>
        public static string res_45 {
            get {
                return ResourceManager.GetString("res_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationRepository - GET method.
        /// </summary>
        public static string res_46 {
            get {
                return ResourceManager.GetString("res_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationRepository - SAVE method.
        /// </summary>
        public static string res_47 {
            get {
                return ResourceManager.GetString("res_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationRepository - DELETE method.
        /// </summary>
        public static string res_48 {
            get {
                return ResourceManager.GetString("res_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MachineRepository - GET method.
        /// </summary>
        public static string res_49 {
            get {
                return ResourceManager.GetString("res_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MachineRepository - SAVE method.
        /// </summary>
        public static string res_50 {
            get {
                return ResourceManager.GetString("res_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MachineRepository - DELETE method.
        /// </summary>
        public static string res_51 {
            get {
                return ResourceManager.GetString("res_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineRepository - GET method.
        /// </summary>
        public static string res_52 {
            get {
                return ResourceManager.GetString("res_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineRepository - SAVE method.
        /// </summary>
        public static string res_53 {
            get {
                return ResourceManager.GetString("res_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineRepository - DELETE method.
        /// </summary>
        public static string res_54 {
            get {
                return ResourceManager.GetString("res_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveUserRepository - GET method.
        /// </summary>
        public static string res_55 {
            get {
                return ResourceManager.GetString("res_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveUserRepository - SAVE method.
        /// </summary>
        public static string res_56 {
            get {
                return ResourceManager.GetString("res_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveUserRepository - DELETE method.
        /// </summary>
        public static string res_57 {
            get {
                return ResourceManager.GetString("res_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeRepository - SyncEmployee.
        /// </summary>
        public static string res_58 {
            get {
                return ResourceManager.GetString("res_58", resourceCulture);
            }
        }
    }
}
