//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.GrafolitOTP
{

    public partial class Osebe_OTP : XPLiteObject
    {
        int fidOsebe;
        [Key(true)]
        public int idOsebe
        {
            get { return fidOsebe; }
            set { SetPropertyValue<int>("idOsebe", ref fidOsebe, value); }
        }
        Vloga_OTP fidVloga;
        [Association(@"Osebe_OTPReferencesVloga_OTP")]
        public Vloga_OTP idVloga
        {
            get { return fidVloga; }
            set { SetPropertyValue<Vloga_OTP>("idVloga", ref fidVloga, value); }
        }
        string fIme;
        [Size(60)]
        public string Ime
        {
            get { return fIme; }
            set { SetPropertyValue<string>("Ime", ref fIme, value); }
        }
        string fPriimek;
        [Size(60)]
        public string Priimek
        {
            get { return fPriimek; }
            set { SetPropertyValue<string>("Priimek", ref fPriimek, value); }
        }
        string fNaslov;
        [Size(160)]
        public string Naslov
        {
            get { return fNaslov; }
            set { SetPropertyValue<string>("Naslov", ref fNaslov, value); }
        }
        DateTime fDatumRojstva;
        public DateTime DatumRojstva
        {
            get { return fDatumRojstva; }
            set { SetPropertyValue<DateTime>("DatumRojstva", ref fDatumRojstva, value); }
        }
        string fEmail;
        [Size(200)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        DateTime fDatumZaposlitve;
        public DateTime DatumZaposlitve
        {
            get { return fDatumZaposlitve; }
            set { SetPropertyValue<DateTime>("DatumZaposlitve", ref fDatumZaposlitve, value); }
        }
        string fUporabniskoIme;
        public string UporabniskoIme
        {
            get { return fUporabniskoIme; }
            set { SetPropertyValue<string>("UporabniskoIme", ref fUporabniskoIme, value); }
        }
        string fGeslo;
        public string Geslo
        {
            get { return fGeslo; }
            set { SetPropertyValue<string>("Geslo", ref fGeslo, value); }
        }
        string fTelefonGSM;
        [Size(60)]
        public string TelefonGSM
        {
            get { return fTelefonGSM; }
            set { SetPropertyValue<string>("TelefonGSM", ref fTelefonGSM, value); }
        }
        int fZunanji;
        public int Zunanji
        {
            get { return fZunanji; }
            set { SetPropertyValue<int>("Zunanji", ref fZunanji, value); }
        }
        string fDelovnoMesto;
        [Size(200)]
        public string DelovnoMesto
        {
            get { return fDelovnoMesto; }
            set { SetPropertyValue<string>("DelovnoMesto", ref fDelovnoMesto, value); }
        }
        string fProfileImage;
        [Size(300)]
        public string ProfileImage
        {
            get { return fProfileImage; }
            set { SetPropertyValue<string>("ProfileImage", ref fProfileImage, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
        int ftsIDOsebe;
        public int tsIDOsebe
        {
            get { return ftsIDOsebe; }
            set { SetPropertyValue<int>("tsIDOsebe", ref ftsIDOsebe, value); }
        }
        [Association(@"StrankaZaposleni_OTPReferencesOsebe_OTP")]
        public XPCollection<StrankaZaposleni_OTP> StrankaZaposleni_OTPs { get { return GetCollection<StrankaZaposleni_OTP>("StrankaZaposleni_OTPs"); } }
    }

}
