//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.GrafolitOTP
{

    public partial class StrankaZaposleni_OTP : XPLiteObject
    {
        int fidStrankaOsebe;
        [Key(true)]
        public int idStrankaOsebe
        {
            get { return fidStrankaOsebe; }
            set { SetPropertyValue<int>("idStrankaOsebe", ref fidStrankaOsebe, value); }
        }
        int fidStranka;
        public int idStranka
        {
            get { return fidStranka; }
            set { SetPropertyValue<int>("idStranka", ref fidStranka, value); }
        }
        Osebe_OTP fidOsebe;
        [Association(@"StrankaZaposleni_OTPReferencesOsebe_OTP")]
        public Osebe_OTP idOsebe
        {
            get { return fidOsebe; }
            set { SetPropertyValue<Osebe_OTP>("idOsebe", ref fidOsebe, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
        int ftsIDOsebe;
        public int tsIDOsebe
        {
            get { return ftsIDOsebe; }
            set { SetPropertyValue<int>("tsIDOsebe", ref ftsIDOsebe, value); }
        }
    }

}
