//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.GrafolitOTP
{

    public partial class TipStranka : XPLiteObject
    {
        int fTipStrankaID;
        [Key(true)]
        public int TipStrankaID
        {
            get { return fTipStrankaID; }
            set { SetPropertyValue<int>("TipStrankaID", ref fTipStrankaID, value); }
        }
        string fKoda;
        [Size(20)]
        public string Koda
        {
            get { return fKoda; }
            set { SetPropertyValue<string>("Koda", ref fKoda, value); }
        }
        string fNaziv;
        [Size(50)]
        public string Naziv
        {
            get { return fNaziv; }
            set { SetPropertyValue<string>("Naziv", ref fNaziv, value); }
        }
        string fOpis;
        [Size(250)]
        public string Opis
        {
            get { return fOpis; }
            set { SetPropertyValue<string>("Opis", ref fOpis, value); }
        }
        int ftsIDOseba;
        public int tsIDOseba
        {
            get { return ftsIDOseba; }
            set { SetPropertyValue<int>("tsIDOseba", ref ftsIDOseba, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
    }

}
