//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace KVP_Obrazci.Domain.GrafolitOTP
{

    public partial class Vloga_OTP : XPLiteObject
    {
        int fidVloga;
        [Key(true)]
        public int idVloga
        {
            get { return fidVloga; }
            set { SetPropertyValue<int>("idVloga", ref fidVloga, value); }
        }
        string fKoda;
        [Size(60)]
        public string Koda
        {
            get { return fKoda; }
            set { SetPropertyValue<string>("Koda", ref fKoda, value); }
        }
        string fNaziv;
        [Size(160)]
        public string Naziv
        {
            get { return fNaziv; }
            set { SetPropertyValue<string>("Naziv", ref fNaziv, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>("ts", ref fts, value); }
        }
        int ftsIDOsebe;
        public int tsIDOsebe
        {
            get { return ftsIDOsebe; }
            set { SetPropertyValue<int>("tsIDOsebe", ref ftsIDOsebe, value); }
        }
        [Association(@"Osebe_OTPReferencesVloga_OTP")]
        public XPCollection<Osebe_OTP> Osebe_OTPs { get { return GetCollection<Osebe_OTP>("Osebe_OTPs"); } }
    }

}
